hh_area_groups:
  - label: "Беларусь"
    host: "rabota.by"
    areas:
      - [16, "Беларусь"]
      - [1007, "Брест"]
      - [2233, "Брестская область"]
      - [1005, "Витебск"]
      - [2234, "Витебская область"]
      - [1003, "Гомель"]
      - [2235, "Гомельская область"]
      - [1006, "Гродно"]
      - [2236, "Гродненская область"]
      - [1002, "Минск"]
      - [2237, "Минская область"]
      - [1004, "Могилев"]
      - [2238, "Могилевская область"]
  - label: "Россия"
    host: "hh.ru"
    areas:
      - [113, "Россия"]
  - label: "Казахстан"
    host: "hh.kz"
    areas:
      - [40, "Казахстан"]
  - label: "Узбекистан"
    host: "hh.uz"
    areas:
      - [97, "Узбекистан"]

benchmark_areas:
  "16": "Беларусь"
  "1": "Москва"
  "2": "Санкт-Петербург"
  "all": "Все регионы"

benchmark_experience_options:
  "": ~
  "noExperience": "Нет опыта"
  "between1And3": "От 1 года до 3 лет"
  "between3And6": "От 3 до 6 лет"
  "moreThan6": "Более 6 лет"

benchmark_period_options: [1, 7, 14, 30, 60, 90, 180, 365]

benchmark_industries:
  "7": "Информационные технологии, системная интеграция, интернет"
  "41": "Розничная торговля"
  "11": "СМИ, маркетинг, реклама, BTL, PR, дизайн, продюсирование"
  "29": "Сельское хозяйство"
  "13": "Строительство, недвижимость, эксплуатация, проектирование"
  "9": "Телекоммуникации, связь"
  "42": "Товары народного потребления (непищевые)"
  "33": "Тяжелое машиностроение"
  "389": "Управление многопрофильными активами"
  "44": "Услуги для бизнеса"
  "49": "Услуги для населения"
  "43": "Финансовый сектор"
  "34": "Химическое производство, удобрения"
  "8": "Электроника, приборостроение, бытовая техника, компьютеры и оргтехника"
  "46": "Энергетика"
